### ISSUE TITLE
What version of Ethernet is required to be supported

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-connect-ethernet#19]
I noticed that there are no normative reference to a specific Ethernet version or versions that is to be supported. I think as an example here is support for 802.1Q required or not by the Ethernet processing at the end of the tunnel?

**Comment by asedeno** [comment]
I think that's largely dependent on what you want to establish a connection between. I don't have any patch cables that list 802.1Q support, for instance.

**Comment by gloinul** [comment]
So I think the main core of this question is to answer what normative reference should be included in this section 6 sentence: 

"When the Context ID is set to zero, the Payload field
   contains a full Layer 2 Ethernet Frame (from the MAC destination
   field until the last byte of the Frame check sequence field)."

To define what a layer 2 Ethernet Frame is.

**Comment by asedeno** [comment]
I don't know how or if I would want to tighten this up, but I am open to suggestions. This description of an Ethernet frame _is_ very loose, but would we want to tighten it up so much that when 802.1πθ comes out it would not be supported even if those Ethernet frames would trivially handled if the endpoints supported it?

**Comment by gloinul** [comment]
Here we might need more Ethernet expertise. Because I have assumed that most Ethernet extensions are compatible within the frame format. However I do think we need to have a normative reference to what encoding 0 really is.

**Comment by asedeno** [comment]
As I understand it, IEEE 802.3 specifies the Ethernet frame, and the 802.1Q tag is optional. 802.1ad (Q-in-Q) allows multiple tags. Beyond those two, I'm not aware of additional alternatives. The tags are detectable because when they are parsed as an EtherType, they present as a tag.

The protocol itself doesn't need to parse the Frame, though implementations might want to inspect them and be clever about something (x-ref: #18).

We should perhaps mention 802.3 / Ethernet II, including optional 802.1Q/802.1ad, though reiterate the recommendation that frames carried by the protocol not be tagged, but have VLANs separated into different conections (x-ref: #15).

Do we need to explicitly mention the other [Ethernet frame types](https://en.wikipedia.org/wiki/Ethernet_frame#Types) here and exclude them? They're not particularly common.

**Comment by gloinul** [comment]
I think we need to consider if the Connect-Ethernet request at least defaults to Ethernet II, and that if one want to use other formats one would add some request parameter to indicate any other format(s) one want to run. 

Referencing 802.3 appears a good normative reference. Saying this without looking into if there are multiple versions of the spec and we need to point to a particular version. Although I would expect fairly good backwards compatibility.
